// src/components/papers/PaperSummary.tsx
"use client";

import ReactMarkdown from "react-markdown";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  LightBulbIcon,
  SparklesIcon,
  TagIcon,
} from "@heroicons/react/24/outline";
import type { ParsedSummary } from "@/lib/papers";

interface PaperSummaryProps {
  summary: ParsedSummary;
}

export function PaperSummary({ summary }: PaperSummaryProps) {
  return (
    <div className="space-y-6">
      {/* TL;DR */}
      {summary.tldr && (
        <Card className="border-blue-200 dark:border-blue-800 bg-blue-50/50 dark:bg-blue-950/20">
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <SparklesIcon className="h-5 w-5 text-blue-600" />
              TL;DR
            </CardTitle>
          </CardHeader>
          <CardContent>
            <p className="text-sm leading-relaxed">{summary.tldr}</p>
          </CardContent>
        </Card>
      )}

      {/* Key Contributions */}
      {summary.contributions && summary.contributions.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <LightBulbIcon className="h-5 w-5 text-amber-600" />
              Key Contributions
            </CardTitle>
          </CardHeader>
          <CardContent>
            <ul className="space-y-2">
              {summary.contributions.map((contribution, index) => (
                <li key={index} className="flex items-start gap-2 text-sm">
                  <span className="shrink-0 w-5 h-5 rounded-full bg-amber-100 dark:bg-amber-900/30 text-amber-700 dark:text-amber-400 flex items-center justify-center text-xs font-medium">
                    {index + 1}
                  </span>
                  <span className="leading-relaxed">{contribution}</span>
                </li>
              ))}
            </ul>
          </CardContent>
        </Card>
      )}

      {/* Keywords */}
      {summary.keywords && summary.keywords.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="text-base flex items-center gap-2">
              <TagIcon className="h-5 w-5 text-purple-600" />
              Keywords
            </CardTitle>
          </CardHeader>
          <CardContent>
            <div className="flex flex-wrap gap-2">
              {summary.keywords.map((keyword) => (
                <span
                  key={keyword}
                  className="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium bg-purple-100 text-purple-700 dark:bg-purple-900/50 dark:text-purple-300"
                >
                  {keyword}
                </span>
              ))}
            </div>
          </CardContent>
        </Card>
      )}

      {/* Model info */}
      <p className="text-xs text-muted-foreground text-right">
        Generated by {summary.model} on{" "}
        {new Date(summary.createdAt).toLocaleDateString()}
      </p>
    </div>
  );
}

/**
 * Fallback for raw markdown summary (legacy format)
 */
export function RawSummary({ content }: { content: string }) {
  return (
    <Card>
      <CardHeader className="pb-2">
        <CardTitle className="text-base flex items-center gap-2">
          <SparklesIcon className="h-5 w-5 text-blue-600" />
          AI Summary
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div className="prose prose-sm dark:prose-invert max-w-none">
          <ReactMarkdown>{content}</ReactMarkdown>
        </div>
      </CardContent>
    </Card>
  );
}
